name: Build craw Compiler and CRASM Assembler
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      # Linux
      - name: Install build tools on Linux
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential llvm-18 llvm-18-dev libpolly-18-dev clang-18
          sudo apt-get zig

      - name: Set LLVM environment variables on Linux
        if: runner.os != 'Windows'
        run: |
          echo "LLVM_SYS_180_PREFIX=/usr/lib/llvm-18" >> $GITHUB_ENV
          echo "LIBCLANG_PATH=/usr/lib/llvm-18/lib"   >> $GITHUB_ENV
          echo "PATH=/usr/lib/llvm-18/bin:$PATH"       >> $GITHUB_ENV

      - name: Build craw on Linux
        if: runner.os != 'Windows'
        run: | 
          make all
          make clean
          make quick
          make test
          make cli
          make clean
        
      # Artifacts
      - name: Upload craw artifact
        uses: actions/upload-artifact@v4
        with:
          name: craw-binary-${{ matrix.os }}
          path: |
            craw*
